import '@/styles/globals.css'
import type { Metadata } from 'next'
import Providers from '@/providers'
import Fonts from '@/styles/fonts'
import { ReactNode } from 'react'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

interface RootLayoutProps {
    children: ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang="en">
            <Providers>
                <body className={Fonts}>{children}</body>
            </Providers>
        </html>
    )
}
